# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkpdfs < Formula
  desc "mkpdfs CLI - Handlebars templates to PDF from your terminal"
  homepage "https://mkpdfs.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.4.0/mkpdfs-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "ae726a5bac3c76faf320997f0f30e986b914116239187939684f7e1255901918"

      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.4.0/mkpdfs-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "2341e7ce12c8bd3117655f89c73bc525f543920470bf805f339da41884dfa335"

      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.4.0/mkpdfs-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "bdd3c180333898222a3d7b81813f529c9383dfdce3ff97c5870a1439c197975e"
      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.4.0/mkpdfs-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "40358d2f1ac2dfcbfc565fafe35684572cfb799815e66a16481d4855ddbee4a3"
      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  test do
    system "#{bin}/mkp", "--version"
  end
end
