# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkpdfs < Formula
  desc "mkpdfs CLI - Handlebars templates to PDF from your terminal"
  homepage "https://mkpdfs.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.2.0/mkpdfs-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "00e8cad0307429b908e681f38e5b4cd61554cc4602cee54605e51c9db1dffa4b"

      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.2.0/mkpdfs-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "e5e5c1e445cda4617afc250c39fabd5fc3058ac20cb01781bcd72a4be0f37f37"

      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.2.0/mkpdfs-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "040c137442e304e891eda494db6586ae7aec41fa610a60aafbf3e224cd9b637a"
      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.2.0/mkpdfs-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "782441b4051012e7abbab1c1f3f5ebda015d185b7d7915c8a66ad0b1f7bf8e68"
      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  test do
    system "#{bin}/mkp", "--version"
  end
end
