# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkpdfs < Formula
  desc "mkpdfs CLI - Handlebars templates to PDF from your terminal"
  homepage "https://mkpdfs.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.1.0/mkpdfs-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "848a125c8dcff1841ed04d130f089a6471348aa67676d1631ae8856bfe162222"

      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.1.0/mkpdfs-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "647804028bd4c9c2f0b89392b2c15ec58c72e357b0dd37482da4cb7d780d00c5"

      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.1.0/mkpdfs-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "aaac181075eccc6bb3ba270f1333209bb4a18243c51850451835ebbbc9967974"
      define_method(:install) do
        bin.install "mkp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkpdfs/mkpdfs-cli/releases/download/v0.1.0/mkpdfs-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "aea04bc9f543c6181430f4ea307a173f6fcacf6dbec458513cd3c74865a75b56"
      define_method(:install) do
        bin.install "mkp"
      end
    end
  end

  test do
    system "#{bin}/mkp", "--version"
  end
end
